[package]
name = "rust-launcher"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_launcher"
src = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
create_process_w = { version = "0.1.2", package = "CreateProcessW" }
